sudo: required
service:
  - docker
before_install:
  - docker build -t pksinghlinux/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pksinghlinux/docker-react npm run test -- --coverage
  




